CREATE TABLE [dbo].[Incidents] (
    [Reference_Number]          NVARCHAR (50)  NOT NULL,
    [Summary]                   NVARCHAR (150) NOT NULL,
    [Created_Date_Time]         NVARCHAR (50)  NOT NULL,
    [Raised_By_Contact]         NVARCHAR (100) NOT NULL,
    [VIP_Raised_By_Contact]     NVARCHAR (50)  NULL,
    [Address_ID]                NVARCHAR (50)  NOT NULL,
    [Address_Line1]             NVARCHAR (50)  NOT NULL,
    [District]                  NVARCHAR (50)  NULL,
    [Region]                    NVARCHAR (50)  NULL,
    [Source]                    NVARCHAR (50)  NOT NULL,
    [Status]                    NVARCHAR (50)  NOT NULL,
    [Response_Level]            NVARCHAR (50)  NOT NULL,
    [Current_Assigned_Group]    NVARCHAR (50)  NULL,
    [Current_Assigned_Analyst]  NVARCHAR (50)  NULL,
    [SLA_Expired]               NVARCHAR (50)  NOT NULL,
    [Breach_Time]               NVARCHAR (50)  NULL,
    [Breaching_In]              NVARCHAR (50)  NULL,
    [Actual_Fix_Date_Time]      NVARCHAR (50)  NULL,
    [Last_Resolution_Date_Time] NVARCHAR (50)  NULL,
    [Last_Resolved_By_User]     NVARCHAR (50)  NULL,
    [Last_Resolving_Group]      NVARCHAR (50)  NULL,
    [First_Contact_Resolution]  BIT            NOT NULL,
    [First_Level_Resolution]    BIT            NOT NULL,
    [Last_Updated_Date_Time]    NVARCHAR (50)  NOT NULL,
    [CI_Asset]                  NVARCHAR (50)  NULL,
    [Business_Service]          NVARCHAR (50)  NULL,
    [Business_Process]          NVARCHAR (50)  NULL,
    [Fault_Category]            NVARCHAR (50)  NOT NULL,
    [Cause_Category]            NVARCHAR (50)  NULL,
    [Fix_Category]              NVARCHAR (50)  NULL,
    [Child_Incident]            BIT            NOT NULL,
    [Impact]                    NVARCHAR (50)  NOT NULL,
    [Urgency]                   NVARCHAR (50)  NOT NULL,
    [Priority]                  NVARCHAR (50)  NOT NULL
);

