CREATE TABLE [dbo].[requests] (
    [ Reference Number ]         VARCHAR (50)  NULL,
    [ Summary ]                  VARCHAR (200) NULL,
    [ Creation Date ]            VARCHAR (50)  NULL,
    [ Raised by Contact ]        VARCHAR (200) NULL,
    [ VIP Raised By Contact ]    VARCHAR (50)  NULL,
    [ Address ID ]               VARCHAR (50)  NULL,
    [ Address Line1 ]            VARCHAR (50)  NULL,
    [ District ]                 VARCHAR (50)  NULL,
    [ Region ]                   VARCHAR (50)  NULL,
    [ Source ]                   VARCHAR (50)  NULL,
    [ Status ]                   VARCHAR (50)  NULL,
    [ Response Level ]           VARCHAR (50)  NULL,
    [ Current Assigned Group ]   VARCHAR (50)  NULL,
    [ Current Assigned Analyst ] VARCHAR (50)  NULL,
    [ SLA% Expired ]             VARCHAR (50)  NULL,
    [ Breach Time ]              VARCHAR (50)  NULL,
    [ Breaching In ]             VARCHAR (50)  NULL,
    [ Actual Fix Date Time ]     VARCHAR (50)  NULL,
    [ Latest Resolution Date ]   VARCHAR (50)  NULL,
    [ Last Resolved by User ]    VARCHAR (50)  NULL,
    [ Last Resolving Group ]     VARCHAR (50)  NULL,
    [ First Contact Resolution ] VARCHAR (50)  NULL,
    [ First Level Resolution ]   VARCHAR (50)  NULL,
    [ Last Update Date Time ]    VARCHAR (50)  NULL,
    [ CI Asset ]                 VARCHAR (50)  NULL,
    [ Business Service ]         VARCHAR (50)  NULL,
    [ Business Process ]         VARCHAR (50)  NULL
);

