# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: 'ASG Subscription(c3b35ca7-4c12-43c6-ab3e-d416225b732c)'
    AuthenticationType: 'server'
    ServerName: 'asgserver.database.windows.net'
    DatabaseName: 'ASGDB'
    SqlUsername: 'dw_admin'
    SqlPassword: 'FredSmith123'
    deployType: 'DacpacTask'
    DeploymentAction: 'Publish'
    DacpacFile: '$(Build.SourcesDirectory)\bin\Debug\AdvWorksProj.dacpac'
    IpDetectionMethod: 'AutoDetect'